### ISSUE TITLE
Question: Why do you apply the shim to a fakeGlobal first?

### ISSUE THREAD

**Issue by silkentrance** [ljharb/simd#1]
Looking at shim.js it seems that it already checks for availability of existing features. Applying the shim to a fakeGlobal makes these extra checks redundant at best.

Or is it because of the integration into esX-shim?

Since the integration is tightly coupled with esX-shim (index.js), would it not be best to remove the now redundant checks from shim.js in order to speed things up?

**Comment by ljharb** [comment]
It's not about "tightly coupled". It's that things should not modify the global environment by default.

At the moment, this module's code is mostly scraped from https://github.com/johnmccutchan/ecmascript_simd, and I'm trying to have as loose coupling with that as I can.

What checks are you referring to? I don't see any in this repo (this repo's issues should only about the `simd` module itself)

**Comment by silkentrance** [comment]
Well, calling the module with a fakeGlobal and then in that module you

line 35ff

```
if (typeof global.SIMD === "undefined") {
  // SIMD module.
  global.SIMD = {};
}
```

and later on you will

e.g. lines 263ff

```
if (typeof SIMD.Bool64x2 === "undefined") {
```

This is what I meant that the checks are basically moot since it will always be the fake global. Yet, and since you incorporate the code from a different source, I see no reason in changing its original behavior.

Thanks for the input!

**Comment by ljharb** [comment]
ah, that makes sense. Yes, it's just because the original source operates on a "global" object, so "SIMD" must exist in order for its checks to work.
