### ISSUE TITLE
Question: in getGlobal you use new Function(...) at the end

### ISSUE THREAD

**Issue by silkentrance** [ljharb/simd#2]
For what purpose do you return the result of new Function("return this;")() at the end of the getGlobal() function?

Would a simple return this; not suffice?

**Comment by ljharb** [comment]
If anything has used `.call`/`.apply`/`.bind` and wrapped this code, `this` won't refer to the global object.

The only way to reliably get the global object in all of browsers, web workers, node, and node-webkit, is to use indirect eval (in this case via the `Function` constructor).

**Comment by silkentrance** [comment]
Thanks for the info!
