### ISSUE TITLE
WebAssembly based SIMD library

### ISSUE THREAD

**Issue by ghost** [ljharb/simd#5]
As I know, SIMD.js removed from browsers and specifications, and merged into WebAssembly. But I suggest to make dedicated SIMD library (and SIMD remake) for JavaScript, independed from ECMAScript specifications? With new syntax, with wrappers, with classes, with TypeScript support?

**Comment by ljharb** [comment]
New syntax would require inclusion in ecmascript.

All of the SIMD stakeholders are only interested in wasm at this time.
